services:
  server:
    container_name: lb1-server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/lb1/server
      - /usr/src/lb1/server/node_modules


  client:
    container_name: lb1-client
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/lb1/client
      - /usr/src/lb1/client/node_modules
    depends_on:
      - server
